### ISSUE TITLE
docker 재시작할 때 mix release 가 동작하지 않는 현상

### ISSUE THREAD

**Issue by hoppang** [hoppang/blueberry#7]
```
  web:
    image: elixir:latest
    restart: always
    stdin_open: true
    tty: true
    depends_on:
```
stdin_open / tty 옵션이 켜져 있으면, mix release 를 재실행할 때

```
Release blueberry-0.1.0 already exists. Overwrite? [Yn]
```
이게 뜨면서 진행이 멈추는 문제가 있음
